import Head from "next/head"
import { GetStaticProps } from "next"
import { Pomodoro } from "../components/pomodoro/Pomodoro"
import { PomodoroState as State } from "../components/pomodoro/PomodoroState"

type User = {
  name: string
}

export default function Home({ user }: { user: User }) {
  const state = new State()

  state.start()

  console.log(user)

  return (
    <div>
      <Head>
        <title>Pomodoro</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Pomodoro state={state} />
    </div>
  )
}

export const getStaticProps: GetStaticProps = async (context) => {
  console.log(context)

  const response = await fetch("http://localhost:3000/api/hello")
  const user = await response.json()

  return {
    props: { user },
  }
}
